image: docker:20.10.2
stages:
  - build
default:
  interruptible: true

variables:
  GIT_DEPTH: "20"
  GIT_FETCH_EXTRA_FLAGS: "--no-tags"
  DOCKER_BUILDKIT: 1
  DOCKER_DRIVER: "overlay2"
  DOCKER_TLS_CERTDIR: "/certs"
  SOURCE_REPOSITORY: registry.gitlab.com/mekkiti/colonial-warfare
  SOURCE_BRANCH: dev

.dind:
  image: docker:20.10.2
  services:
    - docker:20.10.2-dind
  before_script:
    - "[ $CI_REGISTRY ] && command -v docker && echo $CI_JOB_TOKEN | docker login --username gitlab-ci-token --password-stdin $CI_REGISTRY"

build:runner:
  stage: build
  extends: .dind
  script:
    - docker pull ${SOURCE_REPOSITORY}/${SOURCE_BRANCH}
    - docker pull ${CI_REGISTRY_IMAGE}:${SOURCE_BRANCH} || true
    - docker build
      --cache-from ${CI_REGISTRY_IMAGE}:${SOURCE_BRANCH}
      --build-arg BUILDKIT_INLINE_CACHE=1
      --tag ${CI_REGISTRY_IMAGE}:${SOURCE_BRANCH}
      .
    - docker push ${CI_REGISTRY_IMAGE}:${SOURCE_BRANCH}
