# Runs directly local-tagged "cm13-live" image
# you will need a separate mechanism to pull/tag it
# and to create the external data volumes beforehand

version: '3.2'

services:
  cm13-mysql-prod:
    image: mysql:8
    restart: always
    ports:
      - "127.0.0.1:3308:3308"
    environment:
      MYSQL_DATABASE: cm13
      MYSQL_USER: cm13
      MYSQL_PASSWORD: ideallychangethis
      MYSQL_ROOT_PASSWORD: ideallychangethis
    volumes:
      - cm13-mysql-prod:/var/lib/mysql
    networks:
      - cm13-net-prod

  cm13-game-prod:
    image: cm13-live
    ports:
      - "1400:1400"
    volumes:
      - cm13-data-prod:/cm/data
      - type: bind
        source: ./config
        target: /cm/config
        read_only: true
    networks:
      - cm13-net-prod
    depends_on:
      - cm13-mysql-prod

volumes:
  cm13-mysql-prod:
    external: true
  cm13-data-prod:
    external: true

networks:
  cm13-net-prod:
    driver: bridge
