# Runs directly local-tagged "cm13-live" image
#
# you will need a separate mechanism to pull/tag it
# and to create the external data volumes beforehand
#
# The production deployment is meant to use a separate (container or not)
# persistent mysql instance as of current

version: '3.6'

services:
  cm13-game-prod:
    image: cm13-live
    stop_signal: SIGUSR1
    #security_opt:
    #   - seccomp:unconfined
    ports:
      - "1400:1400"
    volumes:
      - cm13-data-staging:/cm/data
      - cm13-cfg-prod:/byond/cfg/
      - type: bind
        source: ./cm-restricted-art/
        target: /cm/icons/custom/
        read_only: true
      - type: bind
        source: ./cm-music
        target: /cm/sound/music
        read_only: true
      - type: bind
        source: ./config
        target: /cm/config
        read_only: true
    network_mode: "host"

volumes:
  cm13-data-prod:
    external: true
  cm13-cfg-prod:
    external: true
