# Runs directly local-tagged "cm13-live" image
#
# you will need a separate mechanism to pull/tag it
# and to create the external data volumes beforehand
#
# The production deployment is meant to use a separate (container or not)
# persistent mysql instance as of current

version: '3.2'

services:
  cm13-game-prod:
    image: cm13-live
    ports:
      - "1400:1400"
    volumes:
      - cm13-data-prod:/cm/data
      - type: bind
        source: ./config
        target: /cm/config
        read_only: true

volumes:
  cm13-data-prod:
    external: true
