# Requires setting
#  - IMAGE_SOURCE: game image that will be ran
# The DD socket will be exposed on a random port
# use docker port to find out

version: '3.2'

services:
  cm13-mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: cm13
      MYSQL_USER: cm13
      MYSQL_PASSWORD: ideallychangethis
      MYSQL_ROOT_PASSWORD: ideallychangethis
    volumes:
      - cm13-mysql-data:/var/lib/mysql
    networks:
      - cm13-net

  cm13-game:
    image: ${IMAGE_SOURCE}
    stop_signal: SIGUSR1
    ports:
      - "1400"
    volumes:
      - cm13-data:/cm/data
    networks:
      - cm13-net
    depends_on:
      - cm13-mysql

volumes:
  cm13-mysql-data:
  cm13-data:

networks:
  cm13-net:
    driver: bridge
