version: '3.2'

services:
  cm13-mysql-prod:
    image: mysql:8
    restart: always
    ports:
      - "127.0.0.1:3307:3306"
    environment:
      MYSQL_DATABASE: cm13
      MYSQL_USER: cm13
      MYSQL_PASSWORD: ideallychangethis
      MYSQL_ROOT_PASSWORD: ideallychangethis
    volumes:
      - cm13-mysql-prod:/var/lib/mysql
    networks:
      - cm13-net-prod

  cm13-game-prod:
    build:
      context: .
    ports:
      - "1400:1400"
    volumes:
      - cm13-data-prod:/cm/data
      - type: bind
        source: ./config
        target: /cm/config
        read_only: true
    networks:
      - cm13-net-prod
    depends_on:
      - cm13-mysql-prod

  cm13-watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60 --label-enable --no-restart --include-stopped

volumes:
  cm13-mysql-prod:
    external: true
  cm13-data-prod:
    external: true

networks:
  cm13-net-prod:
    driver: bridge
